apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  parentRefs:
    - name: external
      namespace: monitoring
  hostnames: ["grafana.kais58.com"]
  rules:
    - backendRefs:
        - name: grafana
          port: 80
