---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/kais58/argo-cluster.git"
      path: kubernetes/apps/kube-system/reloader
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/stakater/charts
      chart: reloader
      targetRevision: 2.2.3
      helm:
        releaseName: reloader
        valueFiles:
          - $repo/kubernetes/apps/kube-system/reloader/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
