---
storageClass:
  create: "true"
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  parameters:
     server: 192.168.1.181
     share: /share/k8s
     subDir:
     mountPermissions: "0"
     #csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
     #csi.storage.k8s.io/provisioner-secret-name: "mount-options"
     #csi.storage.k8s.io/provisioner-secret-namespace: "default"
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  mountOptions:
    - nfsvers=4.1
