controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.kais58.com
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age19934actyek8t7xh4y2nlx4wjtgq0a5d4zszytgd3f58a83ts7ytqasyc63
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ3BycFB0Vy9GTDd5b3FL
        cUN0cmpUY0xHMnNza1BKZ1Y5Q1FvZFdvTGlNCmhwRGU3YTN2UExSWDZtT2JQa2xW
        NC9jcWdHUFhWL2toK2d0cG8zOEJnM3MKLS0tIHdKbzQ3RU9ZWTVMelhHYzFwT05o
        NHVIcGVtMHdJVlJBMzJyOEtpbWNta0UKw6MYjNDMj7vQHj3ofSQTXbdhETKcaKj2
        WgW6xhrulZI12NnyKtcm9sBVIEjAVfBL2GJWaqyafdBgwcgaKbbTlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T17:30:24Z"
  mac: ENC[AES256_GCM,data:3WeRFSXBlTgjsSnLuHuBv+9yhgnAeFRhaW8ff1sJa81j7yUX72c4JO+KPu/SpGXDzlrYussGcBQz2VPVoOQBuafBBjoXdLOHPW+IKsbmDP/R7tiK1IOlI933mNoCpF+JNrZtyA2W/ZlzXsK/Dw1vXjLtFbXKTh4J/taZksajagk=,iv:259mOW3jK+dN6V15yrr8It9rjBEz519HjAB7hcguw/g=,tag:tRBKxj7jmSs1eruCkWs2BQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
