controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.kais58.com
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age19934actyek8t7xh4y2nlx4wjtgq0a5d4zszytgd3f58a83ts7ytqasyc63
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUmhUUjRCR0hBUmdaOGJP
        aGt3SDJCMW40cXJVZjR5TERYWlYxTkpFUlZvCk1SclR0dTJ4NWxLclcyUlVvZmJN
        SG5KUGxkdFcxdi8wYk5sM0FmamJpamcKLS0tIHV5ak9jL2VPT1BadDhEelVzWDg0
        TWllQlZhRVFncUhaNVllekk3OHlncUEKEngtfrq6eL0Uu2o2OIj57QF7a5RHEOBm
        lY14h937/s70HetqyFVOJKhEr/LxZQyt1s81uM2W4I4X7pDwPKQIXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T01:52:35Z"
  mac: ENC[AES256_GCM,data:YYHhl1nTEHdoEnY9oWc/B1wvQqidf+iX2m+cPmyjcKXoYDmf1tGipJljJdDLH2GzJqyvbFJ0WbwWBuk/URX3JbOKwlPyzdssLWQSRwEGgt88aNuY1zfb6AdYrvnUX0ydnDrMGGQAzrFUR+sqGqHhZW61Hf6FMJDzr3zaOSo/lUM=,iv:LMqk1ioncFf11zvZhW5ZI95usH5vwRLjNTkdcSSOT0Y=,tag:eZmYA5Qr2K6Qo5CuLfxg+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
