fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - kais58.com
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age19934actyek8t7xh4y2nlx4wjtgq0a5d4zszytgd3f58a83ts7ytqasyc63
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRU1uZTc5eStELzBPQ0ZN
        UE5wRXZ2Q3dwS2wwYUhJV1BZWlc1bjRod1dZCnFleHlTRWZqN0pOenEwQVB5Zkww
        SWlaTVRpWXRoUXNUL1VIY2JMeXFaV00KLS0tIFNob3pRVmdJQzAvbGFqTnB5TkVl
        UVdPRjVteWFOemo4UlhLNjhWQXhSeEEKnTtxLjRM2vLs2N4nfhjd5JVW12tbhiIM
        mkY/TTkeWBCHhA+RiAZmLpJo47pJrIO/P85IMFoLU1IinOvQSC3/BA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T01:01:10Z"
  mac: ENC[AES256_GCM,data:mnpoUHsw5JZWagH0R6pw7sG+ArP9UfqqWokcwFU65EnqerF+82K0a9h4OthUzoaPMSldDdktQX96kv5DDN6KoGdOuO4QhFXi89Zf0EDdHpQ5MDqgGP8N7EGq9Nu5QXz9F28zvFXuMXAwqXZAUGdVBeHCHYoMFeKN3FjChGdfgh8=,iv:p0wmD4Qhmu4nrDd6RNlRbGuA3QK817Z/a4Q2cIQQpZI=,tag:euz2kw/faV3r2mo3VjUGQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
