fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - kais58.com
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age19934actyek8t7xh4y2nlx4wjtgq0a5d4zszytgd3f58a83ts7ytqasyc63
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOG01T05pczU4UHZlenA4
        THNoN1BxNnJjV0RhdjlsL2prbUREZjdzcFI4Ckl1NFN3U1F5VDdVMnRDdlRRRDk3
        eXR4dDcydXJ0OEpQKzJaZlJZMTBlNzAKLS0tIDhud3QrZlBLaktmdmk5aUNvZFJq
        b0Nzc01RV0g1c3dTVW55RTcybXAydGMK1LnxtO2gOVFo26sRJzJL1c+SQgvde6aZ
        MH23H0+vPIZrkXiI+z3fRmW+g8xcm1tsJvntEsGs4pFTMKw6xpA1UQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T01:52:35Z"
  mac: ENC[AES256_GCM,data:c+NWNYHY9TqfpN9HuJbej/bZWy3pzveTfOQJfe94VmDOXEvvxJx8tfgGa3GUD6KMRCTawaJVqhNbbX0Og8ZarrGHaIWg6mTmP92AnqMdLEp/nhrH6u3fj884PXWcZwIAwjX136cIC7iE/o9lwTjO32pyaURHhSR8vnWZQW2n/ec=,iv:npQTgZlkgYYnNEZFB7RytAVvtDCFYANfEdg6AssosT8=,tag:XquFEVn534z/XgTty0+FfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
