# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - kais58.com
sops:
  age:
    - recipient: age19934actyek8t7xh4y2nlx4wjtgq0a5d4zszytgd3f58a83ts7ytqasyc63
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d3NQSlNCQVhwV3Vtbm5j
        bWIzSTZINmVCT0drNmR0WHJDOWM5MVg5dkJNClNhVzhyT1NSaXcwNGxmSzlLcU1L
        OGFKQ21yTXp4RlVrOTNPSERMWXptYzgKLS0tIHRWaXFKeVBWc09sWEs2d0g1OVBl
        cGloeDdsaUt6OCtDM3NQODRpT29NZVkKibVKLjTSwJmhwuL7ny9v/jyheW4SV+XH
        dOAhAOMuOHPxGgeaz3GR6IwW641Kgcs/EocuEr6NZZSb/Z3rZgo/iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T01:52:35Z"
  mac: ENC[AES256_GCM,data:iqjY+73vGA/CcsIfKHP48ZfmFGRrwb/5J6wFuCuPQF2quw2pLCg8gMG6Y2ksR2NdOD11pd4GMAnC9fjp0nPFTg7KDyx9z2jyaeGTQ/wUXbaQz3J7EYhKBqV6hbDQhwNKIBJ8RP+ENy2EIhVeJnE+cvpokv4dde/skNztlf7Ska8=,iv:z6v5uip1FNTNScWiT+Vgk/6jNxDanOYWsAu556MwRgU=,tag:3++WjWXB9WR1R4Tn75oP5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
