# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - kais58.com
sops:
  age:
    - recipient: age19934actyek8t7xh4y2nlx4wjtgq0a5d4zszytgd3f58a83ts7ytqasyc63
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMW5wdFhIbU95WW9MWllJ
        YmovVjh6R0ZaSksxOVdjSU03djlVRHJJcDFNClVtZktJdGJTSzJLa2NRSEVaOTZQ
        TDd1b09mYVdXSUlvZmh0emJLb2gvZGcKLS0tIGFORGw2ckM3U3hyeEVZN01CSFBv
        b1Nmajk3cHpKSFJaM2J1MjhBVkQzK3MKV8x5mBTyo3B641i6sUmEh7mKgLdtEIxy
        /WAWLZ3eowNxdLc7IHqDs0Ww+5a3OOMroBxy7U9/G1zAT4Wz/s35IA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T01:01:09Z"
  mac: ENC[AES256_GCM,data:f7xXzNLv5p5QET0TrJdOCC6xvbg8CJutk8we6w0MQvtiBOuqPVNSDhYz1DU0aLzqAf9qsjID10kr9zoL/D2GJh2U9Z+dqaKZCWXB6JCk996KP+8I+enZedJ7LHqlyZ/+VO4n9xBxTLOO3nZAO8IfIvh/kfOFfAm+TL+U8lQYIjE=,iv:pPOfYqdi30/Ca5MxUZRnaS63HJ99fjWyOeN/u7YFAe4=,tag:WePHKG6K7Eu4YYqut9MsxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
