---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/kais58/argo-cluster.git"
      path: kubernetes/apps/network/external-dns
      targetRevision: main
      ref: repo
    - repoURL: https://charts.bitnami.com/bitnami
      chart: external-dns
      targetRevision: 9.0.3
      helm:
        releaseName: external-dns
        valueFiles:
          - $repo/kubernetes/apps/network/external-dns/values.yaml
  destination:
    name: in-cluster
    namespace: network
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
