---
global:
  dnsNamespace: "kube-system"
  dnsService: "coredns"
loki:
  schemaConfig:
    configs:
      - from: "2025-01-01"
        store: tsdb
        object_store: "s3"
        schema: "v13"
        index:
          prefix: index_
          period: 24h
# Enable minio for storage
minio:
  enabled: true
