alloy:
  configMap:
    content: |-
      // Write your Alloy config here:
      logging {
        level = "info"
        format = "logfmt"
      }
      loki.write "<LABEL>" {
        endpoint {
          url = "http://loki-gateway"
        }
      }
