---
controllers:
  cloudflare-tunnel:
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: docker.io/cloudflare/cloudflared
          tag: 2025.10.1
        env:
          NO_AUTOUPDATE: true
          TUNNEL_METRICS: 0.0.0.0:8080
          TUNNEL_ORIGIN_ENABLE_HTTP2: true
          TUNNEL_TRANSPORT_PROTOCOL: http2
        envFrom:
          - secretRef:
              name: cloudflare-tunnel-secret
        args: ["tunnel", "run"]
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ready
                port: &port 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 256Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: cloudflare-tunnel
    ports:
      http:
        port: *port
serviceMonitor:
  app:
    serviceName: cloudflare-tunnel
    endpoints:
      - port: http
persistence:
  config-file:
    type: configMap
    name: cloudflare-tunnel-configmap
    globalMounts:
      - path: /etc/cloudflared/config.yaml
        subPath: config.yaml
        readOnly: true
