apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mkODkvtHTsLAfysk4lH+Wt5PAHLDsVU7Ap7ufMo8GyzvNoacLf4XRQ==,iv:Lew7gdbuQkhx1zlej4H/HjIIL8jeyvbTS05Thb1X5g0=,tag:ikTVJSuLAvtcHA7I4EpvsQ==,type:str]
sops:
  age:
    - recipient: age19934actyek8t7xh4y2nlx4wjtgq0a5d4zszytgd3f58a83ts7ytqasyc63
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByck1aRElLMjZReE1tWXUz
        cys0NEo4cDNDNkJUSEJ6cDJqQ2UweDlEMEUwCi9NSE1tS1dZSHdaNm94Wkh5YWhq
        clhwR2lQelNKQ3dlSWZsbUVMMzFOcXMKLS0tIHFsYU02STk0azVKSTBsUkJpaVRP
        YVdSeE5aQk12UUVaMjdnL1ZYOWdJUnMKWVgYMae1yUI5FBU3Z625HOjIc5v07Ivn
        VyeW2A+8YtvSnslJQ8PlSlqE4lUrEMDAGCv7E7lCRcv5VAbO9PaTdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-19T01:01:10Z"
  mac: ENC[AES256_GCM,data:bsgG9z5EPDjbzL9+9GRDO1kRHIfj4frkgGdWivHf8dpCL0xS1U1dDrHj+sI7eVBFZfsFNUg3D+GjVeaTCUMblhEmfaEA3vA/V5KeW6Tc+UO5/+3w/VfZ08U8azmeT1n12HgwV+HBJfx6OB0YmJRHRB2mWLh0rAQ581iUA6/jA6Y=,iv:WIvQ98NsnoXSKCexWynfDlrqh0FHPKA5U1TS7goyZ3k=,tag:6B6iT/sqzVa7GuY8jTHgoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
